feat: lifecycle_policy
terraform-iaac/terraform-aws-efs pull request #1
Opened 2022-09-14 07:53 UTC by gnleong

implemented lifecycle policy configuration

2022-10-11 16:15 UTC, bohdantverdyi requested changes
Hello, could you please update README variables ?

2022-10-12 02:41 UTC, gnleong commented
The README.md is updated with _terraform-docs_ markdown inject. Its output descriptions are missing. So I suggest another PR (doc) for subsequent updates.

2022-10-12 07:09 UTC, bohdantverdyi approved these changes

2022-10-12 07:09 UTC, merged

2022-10-12 07:11 UTC, bohdantverdyi commented
That's okay. New release tag is 2.1.0 
Thank you